### ISSUE TITLE
Running opensesame against current development version of Elektra panics

### ISSUE THREAD

**Issue by atmaxinger** [ElektraInitiative/opensesame#11]
So I have been trying to get opensesame running on the Olimex image.
I've compiled and installed the current `recording` branch of Elektra.

When I perform `cargo run` on opensesame, the following output is issued:

```
thread 'main' panicked at 'Set config failed: Sorry, module  issued error :
: ', src/config.rs:29:17
```

This is the backtrace:
```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   2: opensesame::config::Config::sync
             at ./src/config.rs:29:5
   3: opensesame::config::Config::new
             at ./src/config.rs:20:3
   4: opensesame::main
             at ./src/main.rs:141:27
   5: core::ops::function::FnOnce::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
```

Any help on how to debug/solve this would be highly appreciated.

**Comment by markus2330** [comment]
Did you already see https://github.com/ElektraInitiative/opensesame/pull/10/files?

Maybe @fel115 can help out, he went through similar problems recently.

Btw. as you see the error message is completely unhelpful, the parentKey is missing, and it actually should be **G**et config failed. To fix this first will probably help.

**Comment by atmaxinger** [comment]
Yes, executing the postinst script manually solved this specific issue yesterday. However, there seems to be a bug somewhere, because I actually installed the `.deb` file built with `cargo deb`, and the script complains that it can't find the `kdb` executable. I think that might be caused by the `kdb` executable being installed in `/usr/local/bin` instead of `/usr/bin`.

Anyhow, executing the script `/var/lib/dpkg/info/opensesame.postinst` manually fixes this.

**Comment by atmaxinger** [comment]
> (e.g. as Debian packages)

I have installed Elektra as Debian packages, I created them with the `make package` command. I'm not sure why it wants to install them to `/usr/local`.

**Comment by markus2330** [comment]
It's the default from CMake, you need to set CMAKE_INSTALL_PREFIX=/usr to get proper packages.

**Comment by markus2330** [comment]
Is this fixed now?
